### ISSUE TITLE
Typographic quotes should be language-depdendend

### ISSUE THREAD

**Issue by koppor** [rugk/unicodify#82] opened 2023-09-13 15:07 UTC
## Background

German quotes != English quotes.

## Proposed solution

When I type "something", the quotes should be replaced by the current language of the email.

Meaning „so“ in German :)

## Alternatives

Manually inserting the Unicdode strings.

## Additional context

The help text should also be written with typographic correct quotes:

![image](https://github.com/rugk/unicodify/assets/1366654/546123f5-0e45-4207-87d4-749bd3960045)

**Comment by rugk** [comment] 2023-09-13 21:52
Oh yeah many languages have many different characters for that: https://en.wikipedia.org/wiki/Quotation_mark#Summary_table [The French ones are e.g. also typical](https://en.wikipedia.org/wiki/Guillemet).

> The help text should also be written with typographic correct quotes:

Haha well it is written like that deliberately to demonstrate what is meant with these. Though even the good example looks like using the English quiotes, does not it hmm?

**Comment by rugk** [comment] 2023-09-13 21:53
But yeah just looked and it is hardcoded:
https://github.com/rugk/unicodify/blob/b3943b090207c6848f200fd8bc572f090c2786bc/src/_locales/de/messages.json#L319

Currently, only en-US quotes are supported.

**Comment by tdulcet** [comment] 2023-09-14 08:37
It looks like this is a duplicate of #12.

Anyway, supporting smart quotes for other languages should be relatively easy, although we would need to know what quote characters are on the keyboards for each of those languages. Specifically, we would need to create a huge mapping of "straight quotes" to “smart quotes” for each language. Based on your comments, it sounds like German keyboards may use the same ASCII quote characters (`"` and `'`) as English keyboards, so we would just need to map those to `„/“` and `‚/‘` respectively.

**Comment by rugk** [comment] 2023-09-14 21:25
Duplicate of https://github.com/rugk/unicodify/issues/12

**Closed by rugk** 2023-09-14 21:25 UTC
Labels: enhancement
